version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: instagram_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build: ../backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/instagram_analysis
      REDIS_URL: redis://redis:6379
      APIFY_TOKEN: ${APIFY_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/instagram_analysis
      REDIS_URL: redis://redis:6379
      APIFY_TOKEN: ${APIFY_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../backend:/app
    command: python -m app.services.queue

  scheduler:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/instagram_analysis
      REDIS_URL: redis://redis:6379
      APIFY_TOKEN: ${APIFY_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../backend:/app
    command: python -c "from app.services.scheduler import SchedulerService; SchedulerService().run_scheduler()"

volumes:
  postgres_data:
  redis_data: